server:
  port: 9001

spring:
  application:
    name: event-consumer
  data:
    mongodb:
      host: 10.5.0.2
      port: 27017
      database: events

rabbit:
  url: localhost
  port: 5672
  exchange: events
  queue: poc-events
  user: admin
  pass: admin
  requestedHeartbeat: 60